#-------------------------------
# Site Settings
title: EcommerceMart | Find Fashion, Product Review, and more.
logo: /images/logo.webp
logo_text: EcommerceMart
description: EcommerceMart | Learn how to start and grow your online store with easy ecommerce guides, marketing tips, SEO advice, and practical tools.

#-------------------------------
# Author Global Settings
author:
  - author__name: Coding Rhodes
    author__bio: Learn about Coding Rhodes, an ecommerce expert at EcommerceMart. Discover their insights on ecommerce, tech, and digital marketing.
    author__avatar: /images/author-CodingRhodes.webp


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about-us/'
    - title: 'Contact'
      url: '/contact-us/'
    - title: 'Write for Us'
      url: '/write-for-us/' 


#-------------------------------
# Hero Settings
hero:
  hero__title: First Ecommerce Solutions you ever need.


#-------------------------------
# Blog Settings
blog:
  blog__title: Blog & Resources
  blog__description: Learn how to start and grow your online store with easy ecommerce guides, marketing tips, SEO advice, and practical tools.

#-------------------------------
# Recommended Tag Settings
tag:
  enable: true
  tag__title: Recommended
  tag__name: 


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__title: Get interesting news
  mailchimp__description: Subscribe to our newsletter and weâ€™ll send you the emails of latest posts.
  mailchimp__input__text: Your Email Address...
  mailchimp__button__text: Subscribe
  mailchimp__background__image: 


#-------------------------------
# Footer Settings

# Footer Navigation
footer__menu__settings:
  menu__items:
    - title: 'About'
      url: '/about-us/'
    - title: 'Contact'
      url: '/contact-us/'
    - title: 'Privacy Policy'
      url: '/privacy-policy/'
    - title: 'Disclaimer'
      url: '/disclaimer/'
    - title: 'Terms and Conditions'
      url: '/terms-and-conditions/'
    - title: 'Write for Us'
      url: '/write-for-us/'
    - title: 'Review Policy'
      url: '/review-policy/'
    - title: 'Authors'
      url: '/authors/'


# Social Links
social:
- {icon: "ion-logo-twitter", color: "#55acee", name: Twitter, link: "https://twitter.com"}
- {icon: "ion-logo-facebook", color: "#3b5999", name: Facebook, link: "https://facebook.com"}
- {icon: "ion-logo-pinterest", color: "#bd081c", name: Pinterest, link: "https://pinterest.com"}
- {icon: "ion-logo-dribbble", color: "#ea4c89", name: Dribbble, link: "https://dribbble.com"}
- {icon: "ion-logo-instagram", color: "#e4405f", name: Instagram, link: "https://instagram.com"}


#-------------------------------
# Contact Settings
contact:
  email: codingrhodes@gmail.com # Add your email for contant form

# NOTE

#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  # disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id